### ISSUE TITLE
Suggestion: Add background information about the picture

### ISSUE THREAD

**Issue by vanitasvitae** [danielgimenes/NasaPic#4]
Hi
Why dont you add information about the picture somewhere. You could include the title in the notification.

Nice app btw :)

**Comment by danielgimenes** [comment]
Thanks for the suggestion!

v3.0 has a "description" area on detail screen that does what you mentioned.

BTW, I've just released v3.1 in case you want to check it out. It is way faster and less prone to problems of the NASA API being offline.

**Comment by vanitasvitae** [comment]
NasaPic is still at version 2.5 on FDroid. Do you update the app there?

**Comment by danielgimenes** [comment]
I didn't even know FDroid. I guess they just crawled my app... 

Well, at their wiki about my app (https://f-droid.org/wiki/page/br.com.dgimenes.nasapic), they're saying they can't build it because I'm using Crashlytics... which I'm not sure it is an "issue"... I use it to track errors happening with users that have devices different from mine.

I'm not sure I want to support F-Droid. I would have to remove Crashlytics (and probably not add Google Analytics or any integration), or keep a separate branch, or keep sending them APKs of each version. And they don't give me usage stats, issues report or even feedback comments on the app. They haven't even sent me an e-mail saying they indexed my app (which is ok, the app is free and open source, but I would be happy to know about it).

I'll think about it.

**Comment by vanitasvitae** [comment]
I guess someone, who likes your app has submitted it to FDroid :)
Apps on FDroid must be free of non-free parts and binary blobs, maybe thats why the app is no longer automatically build there.

Of course its your choice if you want to support FDroid. You wont have to send them APKs, since they build everything on their own from source. They do not give out usage statistics because they don't track respecting the privacy of their users.

Indeed, I'd like it if they would inform authors of the apps they are publishing.

In the end its on you to decide how to deal with it :)
